### ISSUE TITLE
HTTPS version is not appearing after the install

### ISSUE THREAD

**Issue by RCAPDART** [ICTman1076/foo_maloja#3]
Hi! Thank you for your plugin, but I could not set up it to test :(

There are two issues, which I faced, so I will create two separate issues here.
First one - I cannot install secure version of the plugin, but insecure is installing correctly.
![1](https://user-images.githubusercontent.com/1285232/89300703-45dd4900-d671-11ea-9e89-7b39127e2461.gif)

Insecure version is installing correctly.

**Comment by RCAPDART** [comment]
Actually I've got the reason of the second bug and make your plugin work in my environment :) I had https redirect and insecure plugin received 301 redirect and post body was empty. 
But I still doesn't understand why my foobar is ignoring installation of the secure plugin.

**Comment by ICTman1076** [comment]
Strange, the secure plugin installed fine on my computer (classic line lol)

I'm working on a 0.0.2 for #4 and so I'll double-check the installer on that version

Thanks for trying the component, will get back to you asap :)

**Comment by RCAPDART** [comment]
I unzipped secure component and replace dll files and now it is working :D
May be it is related to my environment.
Thank you for your quick response 👍
